[36m[2025-05-22 08:55:52] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 08:55:52] [WARNING] Error downloading py_vncorenlp model: [WinError 183] Cannot create a file when that file already exists: './lesson-05/models'[39m
[31m[2025-05-22 08:55:52] [ERROR] Error loading py_vncorenlp model: Please download the VnCoreNLP model![39m
[36m[2025-05-22 09:03:53] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 09:03:53] [WARNING] Error downloading py_vncorenlp model: [WinError 183] Cannot create a file when that file already exists: './lesson-05/models'[39m
[31m[2025-05-22 09:03:53] [ERROR] Error loading py_vncorenlp model: Please download the VnCoreNLP model![39m
[36m[2025-05-22 09:04:52] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 09:04:52] [WARNING] Error downloading py_vncorenlp model: [WinError 183] Cannot create a file when that file already exists: './lesson-05/models'[39m
[31m[2025-05-22 09:04:52] [ERROR] Error loading py_vncorenlp model: Please download the VnCoreNLP model![39m
[36m[2025-05-22 09:09:42] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 09:09:42] [WARNING] Error downloading py_vncorenlp model: [WinError 183] Cannot create a file when that file already exists: './lesson-05/models'[39m
[31m[2025-05-22 09:09:42] [ERROR] Error loading py_vncorenlp model: Please download the VnCoreNLP model![39m
[36m[2025-05-22 09:10:14] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 09:10:14] [WARNING] Error downloading py_vncorenlp model: [WinError 183] Cannot create a file when that file already exists: './lesson-05/models'[39m
[31m[2025-05-22 09:10:14] [ERROR] Error loading py_vncorenlp model: Please download the VnCoreNLP model![39m
[36m[2025-05-22 09:18:00] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 09:18:00] [WARNING] Error downloading py_vncorenlp model: [WinError 183] Cannot create a file when that file already exists: 'C:/Users/VICTUS/Documents/developer/uit-practicalLesson-sML/lesson-05/models'[39m
[31m[2025-05-22 09:18:00] [ERROR] Error loading py_vncorenlp model: Please download the VnCoreNLP model![39m
[36m[2025-05-22 09:32:29] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 09:33:58] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 09:33:58] [ERROR] Error loading train dataset: File ./lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 09:33:58] [ERROR] The pipeline has been interrupted just now![39m
[36m[2025-05-22 09:35:48] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 09:35:59] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 09:35:59] [ERROR] Error loading train dataset: File /lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 09:35:59] [ERROR] The pipeline has been interrupted just now![39m
[36m[2025-05-22 09:43:58] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 09:44:10] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 09:44:10] [ERROR] Error loading train dataset: File lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 09:44:10] [ERROR] The pipeline has been interrupted just now![39m
[36m[2025-05-22 09:46:43] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 09:46:54] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 09:46:54] [ERROR] Error loading train dataset: File lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 09:46:54] [ERROR] Error loading dev dataset: File lesson-05/data/UIT-VSFC-dev.json does not exist[39m
[31m[2025-05-22 09:46:54] [ERROR] Error loading test dataset: File lesson-05/data/UIT-VSFC-test.json does not exist[39m
[32m[2025-05-22 09:46:54] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 09:56:10] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 09:56:21] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 09:56:21] [ERROR] Error loading train dataset: File lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 09:56:21] [ERROR] The pipeline has been interrupted just now![39m
[36m[2025-05-22 09:57:24] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 09:57:35] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 09:57:35] [ERROR] Error loading train dataset: File lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 09:57:35] [ERROR] The pipeline has been interrupted just now![39m
[36m[2025-05-22 10:04:16] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 10:04:27] [INFO] Start loading datasets ...[39m
[31m[2025-05-22 10:04:27] [ERROR] Error loading train dataset: File lesson-05/data/UIT-VSFC-train.json does not exist[39m
[31m[2025-05-22 10:04:27] [ERROR] The pipeline has been interrupted just now![39m
[36m[2025-05-22 10:05:43] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 10:05:54] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 10:05:54] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 10:06:41] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 10:06:52] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 10:06:52] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 10:10:54] [INFO] Start downloading py_vncorenlp model ...[39m
[36m[2025-05-22 10:11:05] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 10:11:05] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 10:11:42] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 10:11:42] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 10:11:53] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 10:11:53] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 10:17:01] [INFO] Starting main pipeline...[39m
[36m[2025-05-22 10:17:01] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 10:17:01] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 10:17:16] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 10:17:16] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 10:17:17] [INFO] Example tokenization: ['hello m·∫•y b√† n·ªôi Vi·ªát_Nam'][39m
[36m[2025-05-22 10:17:17] [INFO] Starting tokenization of datasets...[39m
[32m[2025-05-22 10:17:55] [SUCCESS] Dataset tokenization completed successfully![39m
[36m[2025-05-22 10:17:55] [INFO] Tokenized training data head:[39m
[36m[2025-05-22 10:17:55] [INFO] 
                                            sentence sentiment             topic                                 tokenized_sentence
0                          slide gi√°o tr√¨nh ƒë·∫ßy ƒë·ªß .  positive  training_program                          slide gi√°o_tr√¨nh ƒë·∫ßy_ƒë·ªß .
1     nhi·ªát t√¨nh gi·∫£ng d·∫°y , g·∫ßn g≈©i v·ªõi sinh vi√™n .  positive          lecturer     nhi·ªát_t√¨nh gi·∫£ng_d·∫°y , g·∫ßn_g≈©i v·ªõi sinh_vi√™n .
2               ƒëi h·ªçc ƒë·∫ßy ƒë·ªß full ƒëi·ªÉm chuy√™n c·∫ßn .  negative  training_program               ƒëi h·ªçc ƒë·∫ßy_ƒë·ªß full ƒëi·ªÉm chuy√™n_c·∫ßn .
3  ch∆∞a √°p d·ª•ng c√¥ng ngh·ªá th√¥ng tin v√† c√°c thi·∫øt ...  negative          lecturer  ch∆∞a √°p_d·ª•ng c√¥ng_ngh·ªá_th√¥ng_tin v√† c√°c thi·∫øt_...
4  th·∫ßy gi·∫£ng b√†i hay , c√≥ nhi·ªÅu b√†i t·∫≠p v√≠ d·ª• ng...  positive          lecturer  th·∫ßy gi·∫£ng b√†i hay , c√≥ nhi·ªÅu b√†i_t·∫≠p v√≠_d·ª• ng...[39m
[36m[2025-05-22 10:17:55] [INFO] Tokenized development data head:[39m
[36m[2025-05-22 10:17:55] [INFO] 
                                            sentence sentiment             topic                                 tokenized_sentence
0                           gi√°o tr√¨nh ch∆∞a c·ª• th·ªÉ .  negative  training_program                           gi√°o_tr√¨nh ch∆∞a c·ª•_th·ªÉ .
1                                   gi·∫£ng bu·ªìn ng·ªß .  negative          lecturer                                   gi·∫£ng bu·ªìn_ng·ªß .
2                     gi√°o vi√™n vui t√≠nh , t·∫≠n t√¢m .  positive          lecturer                     gi√°o_vi√™n vui_t√≠nh , t·∫≠n_t√¢m .
3  gi·∫£ng vi√™n n√™n giao b√†i t·∫≠p nhi·ªÅu h∆°n , chia n...  negative          lecturer  gi·∫£ng_vi√™n n√™n giao b√†i_t·∫≠p nhi·ªÅu h∆°n , chia n...
4  gi·∫£ng vi√™n c·∫ßn gi·∫£ng b√†i chi ti·∫øt h∆°n , ƒëi s√¢u...  negative          lecturer  gi·∫£ng_vi√™n c·∫ßn gi·∫£ng b√†i chi_ti·∫øt h∆°n , ƒëi_s√¢u...[39m
[36m[2025-05-22 10:17:55] [INFO] Tokenized test data head:[39m
[36m[2025-05-22 10:17:55] [INFO] 
                                            sentence sentiment     topic                                 tokenized_sentence
0                           n√≥i ti·∫øng anh l∆∞u lo√°t .  positive  lecturer                           n√≥i ti·∫øng anh l∆∞u_lo√°t .
1                           gi√°o vi√™n r·∫•t vui t√≠nh .  positive  lecturer                           gi√°o_vi√™n r·∫•t vui_t√≠nh .
2                                    c√¥ max c√≥ t√¢m .  positive  lecturer                                    c√¥ max c√≥ t√¢m .
3                       gi·∫£ng b√†i thu h√∫t , d√≠ d·ªèm .  positive  lecturer                       gi·∫£ng b√†i thu_h√∫t , d√≠_d·ªèm .
4  gi√°o vi√™n kh√¥ng gi·∫£ng d·∫°y ki·∫øn th·ª©c , h∆∞·ªõng d·∫´...  negative  lecturer  gi√°o_vi√™n kh√¥ng gi·∫£ng_d·∫°y ki·∫øn_th·ª©c , h∆∞·ªõng_d·∫´...[39m
[32m[2025-05-22 10:17:55] [SUCCESS] Pipeline executed successfully![39m
[36m[2025-05-22 10:26:59] [INFO] Starting main pipeline...[39m
[36m[2025-05-22 10:26:59] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 10:26:59] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 10:27:10] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 10:27:10] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 10:27:10] [INFO] Starting tokenization of datasets...[39m
[32m[2025-05-22 10:27:26] [SUCCESS] Dataset tokenization completed successfully![39m
[32m[2025-05-22 10:27:26] [SUCCESS] Pipeline executed successfully![39m
[36m[2025-05-22 15:45:15] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 15:45:15] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[2025-05-22 16:10:56] [INFO] Start loading py_vncorenlp
[36m[2025-05-22 16:10:56] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 16:10:56] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[32m[2025-05-22 16:11:07] [SUCCESS] Loading py_vncorenlp model has been completed successfully![39m
[36m[2025-05-22 16:11:07] [INFO] Start loading PhoBert model and (vinai/phobert-base-v2)[39m
[2025-05-22 16:14:48] [INFO] Start loading py_vncorenlp
[36m[2025-05-22 16:14:48] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 16:14:48] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[32m[2025-05-22 16:14:59] [SUCCESS] Loading py_vncorenlp model has been completed successfully![39m
[36m[2025-05-22 16:14:59] [INFO] Start loading PhoBert model and (vinai/phobert-base-v2)[39m
[36m[2025-05-22 16:22:42] [INFO] Starting main pipeline...[39m
[36m[2025-05-22 16:22:42] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 16:22:42] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 16:22:53] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 16:22:53] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 16:22:53] [INFO] Starting tokenization of datasets...[39m
[32m[2025-05-22 16:23:09] [SUCCESS] Dataset tokenization completed successfully![39m
[36m[2025-05-22 16:23:09] [INFO] Start saving word-segmented datasets ...[39m
[31m[2025-05-22 16:23:09] [ERROR] Error saving datasets: Cannot save file into a non-existent directory: 'lesson-05\data\wordSegmentedDataset'[39m
[32m[2025-05-22 16:23:09] [SUCCESS] Pipeline executed successfully![39m
[36m[2025-05-22 16:25:27] [INFO] Starting main pipeline...[39m
[36m[2025-05-22 16:25:27] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 16:25:27] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 16:25:38] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 16:25:38] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 16:25:38] [INFO] Starting tokenization of datasets...[39m
[32m[2025-05-22 16:25:53] [SUCCESS] Dataset tokenization completed successfully![39m
[36m[2025-05-22 16:25:53] [INFO] Start saving word-segmented datasets ...[39m
[31m[2025-05-22 16:25:53] [ERROR] Error saving datasets: Cannot save file into a non-existent directory: 'lesson-05\data\wordSegmentedDataset'[39m
[36m[2025-05-22 16:28:12] [INFO] Starting main pipeline...[39m
[36m[2025-05-22 16:28:12] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 16:28:12] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 16:28:23] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 16:28:23] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 16:28:23] [INFO] Starting tokenization of datasets...[39m
[32m[2025-05-22 16:28:41] [SUCCESS] Dataset tokenization completed successfully![39m
[36m[2025-05-22 16:28:41] [INFO] Start saving word-segmented datasets ...[39m
[32m[2025-05-22 16:28:41] [SUCCESS] Pipeline executed successfully![39m
[36m[2025-05-22 16:39:05] [INFO] Starting main pipeline...[39m
[36m[2025-05-22 16:39:05] [INFO] Start downloading py_vncorenlp model ...[39m
[33m[2025-05-22 16:39:05] [WARNING] Error downloading py_vncorenlp model: download_model() got an unexpected keyword argument 'annotators'[39m
[36m[2025-05-22 16:39:16] [INFO] Start loading datasets ...[39m
[32m[2025-05-22 16:39:16] [SUCCESS] Loading datasets has been completed successfully![39m
[36m[2025-05-22 16:39:16] [INFO] Starting tokenization of datasets...[39m
[32m[2025-05-22 16:39:32] [SUCCESS] Dataset tokenization completed successfully![39m
[36m[2025-05-22 16:39:32] [INFO] Start saving word-segmented datasets ...[39m
[36m[2025-05-22 16:39:32] [INFO] Datasets saved successfully.[39m
[32m[2025-05-22 16:39:32] [SUCCESS] Pipeline executed successfully![39m
[32m[2025-05-22 17:02:50] [SUCCESS] Loading datasets have been completed successfully![39m
[36m[2025-05-22 17:02:50] [INFO] Start loading PhoBert model and (vinai/phobert-base-v2)[39m
[36m[2025-05-22 17:04:22] [INFO] Start loading segmented datasets ...[39m
[32m[2025-05-22 17:04:22] [SUCCESS] Loading datasets have been completed successfully![39m
[36m[2025-05-22 17:04:22] [INFO] Start loading PhoBert model and (vinai/phobert-base-v2)[39m
[36m[2025-05-22 20:32:30] [INFO] Start loading segmented datasets ...[39m
[32m[2025-05-22 20:32:30] [SUCCESS] Loading datasets have been completed successfully![39m
[36m[2025-05-22 20:32:30] [INFO] Start loading PhoBert model and (vinai/phobert-base-v2)[39m
